// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_I9T4sSZbIPuW9e_yG4tkxjNqfvyYXfA',
    appId: '1:781029316574:web:11ca8b6b70160128502f4f',
    messagingSenderId: '781029316574',
    projectId: 'expenseapp-11b49',
    authDomain: 'expenseapp-11b49.firebaseapp.com',
    storageBucket: 'expenseapp-11b49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBl1Mmt67ClGSHxYWnaDtSO1QIbjoy7U',
    appId: '1:781029316574:android:eab6c639f1082ada502f4f',
    messagingSenderId: '781029316574',
    projectId: 'expenseapp-11b49',
    storageBucket: 'expenseapp-11b49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVquowwZJ0fIt4lKIXkEjOdMk1yakEVdc',
    appId: '1:781029316574:ios:e50f6ab59ace559c502f4f',
    messagingSenderId: '781029316574',
    projectId: 'expenseapp-11b49',
    storageBucket: 'expenseapp-11b49.appspot.com',
    iosBundleId: 'com.expensesTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVquowwZJ0fIt4lKIXkEjOdMk1yakEVdc',
    appId: '1:781029316574:ios:1841f08e35abb12d502f4f',
    messagingSenderId: '781029316574',
    projectId: 'expenseapp-11b49',
    storageBucket: 'expenseapp-11b49.appspot.com',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_I9T4sSZbIPuW9e_yG4tkxjNqfvyYXfA',
    appId: '1:781029316574:web:7f6d06684416c3db502f4f',
    messagingSenderId: '781029316574',
    projectId: 'expenseapp-11b49',
    authDomain: 'expenseapp-11b49.firebaseapp.com',
    storageBucket: 'expenseapp-11b49.appspot.com',
  );

}